CI: Install python whenever --features="pyo3" is provided
python3.x and python3.x-devel are required to be installed whenever we
run cargo providing '--features="pyo3"'.

For example:
cargo clippy --bin stubgen --features="pyo3" -- -D warnings
<..>
error: failed to run custom build command for `pyo3-build-config v0.25.1`

Caused by:
  process didn't exit successfully:
       `/root/qrmi/target/debug/build/pyo3-build-config-a8e1fd1d997cbc8b/build-script-build`
       (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_CONFIG_FILE
  cargo:rerun-if-env-changed=PYO3_NO_PYTHON
  cargo:rerun-if-env-changed=PYO3_ENVIRONMENT_SIGNATURE
  cargo:rerun-if-env-changed=PYO3_PYTHON
  cargo:rerun-if-env-changed=VIRTUAL_ENV
  cargo:rerun-if-env-changed=CONDA_PREFIX
  cargo:rerun-if-env-changed=PATH

  --- stderr
  error: no Python 3.x interpreter found
warning: build failed, waiting for other jobs to finish...

Signed-off-by: Claudio Carvalho <cclaudio@ibm.com>