Modify the pull-request workflow to run within ubi8 container (#84)
* CI: Install CI required packages from distro

Not all packages required by the CI are installed in the UBI image. This
patch creates the file requirements-distro.txt with the list of required
packages and use the file to install the packages.

The python3.12 installed using the github actions/setup-python@v6
requires a glibc version that is not available in the UBI image, so we
also must install the python package from the distro. Since the
python-version is an input for the workflow, we don't keep the python
package in the  requirements-distro.txt

Additionally, we also need to install pip from the distro. In order to
avoid incompatibility issues we no longer run pip upgrade.

Signed-off-by: Claudio Carvalho <cclaudio@ibm.com>

* CI: Keep python-version description clean in the workflow input

There is no need to have a comment that fully describes the input since
it is already described in the inputs section.

Signed-off-by: Claudio Carvalho <cclaudio@ibm.com>

* CI: Install python whenever --features="pyo3" is provided

python3.x and python3.x-devel are required to be installed whenever we
run cargo providing '--features="pyo3"'.

For example:
cargo clippy --bin stubgen --features="pyo3" -- -D warnings
<..>
error: failed to run custom build command for `pyo3-build-config v0.25.1`

Caused by:
  process didn't exit successfully:
       `/root/qrmi/target/debug/build/pyo3-build-config-a8e1fd1d997cbc8b/build-script-build`
       (exit status: 1)
  --- stdout
  cargo:rerun-if-env-changed=PYO3_CONFIG_FILE
  cargo:rerun-if-env-changed=PYO3_NO_PYTHON
  cargo:rerun-if-env-changed=PYO3_ENVIRONMENT_SIGNATURE
  cargo:rerun-if-env-changed=PYO3_PYTHON
  cargo:rerun-if-env-changed=VIRTUAL_ENV
  cargo:rerun-if-env-changed=CONDA_PREFIX
  cargo:rerun-if-env-changed=PATH

  --- stderr
  error: no Python 3.x interpreter found
warning: build failed, waiting for other jobs to finish...

Signed-off-by: Claudio Carvalho <cclaudio@ibm.com>

* CI: Modify the pull-request CI to build for ubi8

Keep the pull-request CI consistent with the release CI,
which is building for ubi8.

Fixes #82

Signed-off-by: Claudio Carvalho <cclaudio@ibm.com>

---------

Signed-off-by: Claudio Carvalho <cclaudio@ibm.com>